In [1]:
import pandas as pd

df = pd.read_excel("Telco_customer_churn.xlsx")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [2]:
df.shape

(7043, 33)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 1.8+ MB

In [4]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [5]:
#Checking for null values
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [20]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

In [21]:
df.columns

Index(['customerid', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure_months', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn_label',
       'churn_value', 'churn_score', 'cltv', 'churn_reason'],
      dtype='str')

In [8]:
# Checking for duplicate Customers ID's

df['customerid'].duplicated().sum()

np.int64(0)

In [9]:
# Dropping columns 'count', 'country', 'state', 'city', 'zip_code', 'lat_long', 'latitude', 'longitude' as they don't contribute to customer churn analysis

drop_cols = [
    'count',
    'country',
    'state',
    'city',
    'zip_code',
    'lat_long',
    'latitude',
    'longitude'
]

df.drop(columns=drop_cols, inplace=True)

In [10]:
df.dtypes

customerid               str
gender                   str
senior_citizen           str
partner                  str
dependents               str
tenure_months          int64
phone_service            str
multiple_lines           str
internet_service         str
online_security          str
online_backup            str
device_protection        str
tech_support             str
streaming_tv             str
streaming_movies         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges         object
churn_label              str
churn_value            int64
churn_score            int64
cltv                   int64
churn_reason             str
dtype: object

In [11]:
#Converting 'total_charges' to a numeric column

df['total_charges'] = pd.to_numeric(df['total_charges'], errors='coerce')

In [12]:
#Count of missing values created

df['total_charges'].isnull().sum()

np.int64(11)

In [13]:
# Remove rows with missing Total Charges (11 rows, ~0.16% of the dataset)

df = df.dropna(subset=['total_charges'])

In [14]:
#Checking for unique values

for col in df.select_dtypes('object'):
    print(col)
    print(df[col].unique())

customerid
<StringArray>
['3668-QPYBK', '9237-HQITU', '9305-CDSKC', '7892-POOKP', '0280-XJGEX',
 '4190-MFLUW', '8779-QRDMV', '1066-JKSGK', '6467-CHFZW', '8665-UTDHZ',
 ...
 '0871-OPBXW', '3605-JISKB', '9767-FFLEM', '8456-QDAVC', '7750-EYXWZ',
 '2569-WGERO', '6840-RESVB', '2234-XADUH', '4801-JZAZL', '3186-AJIEK']
Length: 7032, dtype: str
gender
<StringArray>
['Male', 'Female']
Length: 2, dtype: str
senior_citizen
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
partner
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
phone_service
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
multiple_lines
<StringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str
internet_service
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
online_security
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
online_backup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
device_protection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
tech_support
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
streaming_tv
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
streaming_movies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
contract
<StringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str
paperless_billing
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
payment_method
<StringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
churn_label
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
churn_reason
<StringArray>
[             'Competitor made better offer',
                                     'Moved',
             'Competitor had better devices',
 'Competitor offered higher download speeds',
              'Competitor offered more data',
                            'Price too high',
                   'Product dissatisfaction',
                   'Service dissatisfaction',
           'Lack of self-service on Website',
                       'Network reliability',
                 'Limited range of services',
  'Lack of affordable download/upload speed',
                     'Long distance charges',
                        'Extra data charges',
                                'Don't know',
          'Poor expertise of online support',
           'Poor expertise of phone support',
              'Attitude of service provider',
                'Attitude of support person',
                                  'Deceased',
                                         nan]
Length: 21, dtype: str

C:\Users\DELL\AppData\Local\Temp\ipykernel_30832\3819435612.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes('object'):

In [15]:
df.to_csv("clean_telco_churn.csv", index=False)

In [16]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="Kavya@2905",
    host="localhost",
    port=5432,
    database="customer_churn_analysis"
)

engine = create_engine(url)

In [22]:
df.to_sql(
    "telco_customer_churn",
    engine,
    if_exists="replace",
    index=False
)

32